//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEconomy_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.export = new HashSet<export>();
            this.gdp = new HashSet<gdp>();
            this.gdpgrowth = new HashSet<gdpgrowth>();
            this.import1 = new HashSet<import1>();
            this.inflation = new HashSet<inflation>();
            this.national_debt = new HashSet<national_debt>();
            this.population = new HashSet<population>();
            this.unemployment = new HashSet<unemployment>();
        }
    
        public int IdCountry { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<export> export { get; set; }
        public virtual ICollection<gdp> gdp { get; set; }
        public virtual ICollection<gdpgrowth> gdpgrowth { get; set; }
        public virtual ICollection<import1> import1 { get; set; }
        public virtual ICollection<inflation> inflation { get; set; }
        public virtual ICollection<national_debt> national_debt { get; set; }
        public virtual ICollection<population> population { get; set; }
        public virtual ICollection<unemployment> unemployment { get; set; }
    }
}
