//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEconomy_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class state_economyEntities : DbContext
    {
        public state_economyEntities()
            : base("name=state_economyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<country> country { get; set; }
        public DbSet<export> export { get; set; }
        public DbSet<gdp> gdp { get; set; }
        public DbSet<gdpgrowth> gdpgrowth { get; set; }
        public DbSet<import1> import1 { get; set; }
        public DbSet<inflation> inflation { get; set; }
        public DbSet<national_debt> national_debt { get; set; }
        public DbSet<population> population { get; set; }
        public DbSet<unemployment> unemployment { get; set; }
    }
}
